// Copyright 2019 The go-github AUTHORS. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by gen-stringify-tests; DO NOT EDIT.

package sophoscentral

import (
	"testing"
)

func Float64(v float64) *float64 { return &v }

func TestEndpoints_String(t *testing.T) {
	v := Endpoints{
		Pages: &PagesByFromKey{},
	}
	want := `sophoscentral.Endpoints{Pages:sophoscentral.PagesByFromKey{}}`
	if got := v.String(); got != want {
		t.Errorf("Endpoints.String = %v, want %v", got, want)
	}
}

func TestRate_String(t *testing.T) {
	v := Rate{
		Limit:     0,
		Remaining: 0,
		Reset:     Timestamp{},
	}
	want := `sophoscentral.Rate{Limit:0, Remaining:0, Reset:sophoscentral.Timestamp{0001-01-01 00:00:00 +0000 UTC}}`
	if got := v.String(); got != want {
		t.Errorf("Rate.String = %v, want %v", got, want)
	}
}
