// Copyright 2017 The go-github AUTHORS. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by gen-accessors; DO NOT EDIT.

package sophoscentral

import (
	"testing"
	"time"
)

func TestAbuseRateLimitError_GetRetryAfter(tt *testing.T) {
	var zeroValue time.Duration
	a := &AbuseRateLimitError{RetryAfter: &zeroValue}
	a.GetRetryAfter()
	a = &AbuseRateLimitError{}
	a.GetRetryAfter()
	a = nil
	a.GetRetryAfter()
}

func TestAssociatedPerson_GetID(tt *testing.T) {
	var zeroValue string
	a := &AssociatedPerson{ID: &zeroValue}
	a.GetID()
	a = &AssociatedPerson{}
	a.GetID()
	a = nil
	a.GetID()
}

func TestAssociatedPerson_GetName(tt *testing.T) {
	var zeroValue string
	a := &AssociatedPerson{Name: &zeroValue}
	a.GetName()
	a = &AssociatedPerson{}
	a.GetName()
	a = nil
	a.GetName()
}

func TestEndpoints_GetPages(tt *testing.T) {
	e := &Endpoints{}
	e.GetPages()
	e = nil
	e.GetPages()
}

func TestHealth_GetOverall(tt *testing.T) {
	var zeroValue string
	h := &Health{Overall: &zeroValue}
	h.GetOverall()
	h = &Health{}
	h.GetOverall()
	h = nil
	h.GetOverall()
}

func TestItem_GetAssociatedPerson(tt *testing.T) {
	i := &Item{}
	i.GetAssociatedPerson()
	i = nil
	i.GetAssociatedPerson()
}

func TestItem_GetEncryption(tt *testing.T) {
	i := &Item{}
	i.GetEncryption()
	i = nil
	i.GetEncryption()
}

func TestItem_GetGroup(tt *testing.T) {
	i := &Item{}
	i.GetGroup()
	i = nil
	i.GetGroup()
}

func TestItem_GetHealth(tt *testing.T) {
	i := &Item{}
	i.GetHealth()
	i = nil
	i.GetHealth()
}

func TestItem_GetHostname(tt *testing.T) {
	var zeroValue string
	i := &Item{Hostname: &zeroValue}
	i.GetHostname()
	i = &Item{}
	i.GetHostname()
	i = nil
	i.GetHostname()
}

func TestItem_GetID(tt *testing.T) {
	var zeroValue string
	i := &Item{ID: &zeroValue}
	i.GetID()
	i = &Item{}
	i.GetID()
	i = nil
	i.GetID()
}

func TestItem_GetLastSeenAt(tt *testing.T) {
	var zeroValue string
	i := &Item{LastSeenAt: &zeroValue}
	i.GetLastSeenAt()
	i = &Item{}
	i.GetLastSeenAt()
	i = nil
	i.GetLastSeenAt()
}

func TestItem_GetLockdown(tt *testing.T) {
	i := &Item{}
	i.GetLockdown()
	i = nil
	i.GetLockdown()
}

func TestItem_GetOS(tt *testing.T) {
	i := &Item{}
	i.GetOS()
	i = nil
	i.GetOS()
}

func TestItem_GetTamperProtectionEnabled(tt *testing.T) {
	var zeroValue bool
	i := &Item{TamperProtectionEnabled: &zeroValue}
	i.GetTamperProtectionEnabled()
	i = &Item{}
	i.GetTamperProtectionEnabled()
	i = nil
	i.GetTamperProtectionEnabled()
}

func TestItem_GetTenant(tt *testing.T) {
	i := &Item{}
	i.GetTenant()
	i = nil
	i.GetTenant()
}

func TestItem_GetType(tt *testing.T) {
	var zeroValue string
	i := &Item{Type: &zeroValue}
	i.GetType()
	i = &Item{}
	i.GetType()
	i = nil
	i.GetType()
}

func TestOS_GetBuild(tt *testing.T) {
	var zeroValue int64
	o := &OS{Build: &zeroValue}
	o.GetBuild()
	o = &OS{}
	o.GetBuild()
	o = nil
	o.GetBuild()
}

func TestPagesByFromKey_GetFromKey(tt *testing.T) {
	var zeroValue string
	p := &PagesByFromKey{FromKey: &zeroValue}
	p.GetFromKey()
	p = &PagesByFromKey{}
	p.GetFromKey()
	p = nil
	p.GetFromKey()
}

func TestPagesByFromKey_GetItems(tt *testing.T) {
	var zeroValue int
	p := &PagesByFromKey{Items: &zeroValue}
	p.GetItems()
	p = &PagesByFromKey{}
	p.GetItems()
	p = nil
	p.GetItems()
}

func TestPagesByFromKey_GetMaxSize(tt *testing.T) {
	var zeroValue int
	p := &PagesByFromKey{MaxSize: &zeroValue}
	p.GetMaxSize()
	p = &PagesByFromKey{}
	p.GetMaxSize()
	p = nil
	p.GetMaxSize()
}

func TestPagesByFromKey_GetNextKey(tt *testing.T) {
	var zeroValue string
	p := &PagesByFromKey{NextKey: &zeroValue}
	p.GetNextKey()
	p = &PagesByFromKey{}
	p.GetNextKey()
	p = nil
	p.GetNextKey()
}

func TestPagesByFromKey_GetSize(tt *testing.T) {
	var zeroValue int
	p := &PagesByFromKey{Size: &zeroValue}
	p.GetSize()
	p = &PagesByFromKey{}
	p.GetSize()
	p = nil
	p.GetSize()
}

func TestPagesByFromKey_GetTotal(tt *testing.T) {
	var zeroValue int
	p := &PagesByFromKey{Total: &zeroValue}
	p.GetTotal()
	p = &PagesByFromKey{}
	p.GetTotal()
	p = nil
	p.GetTotal()
}

func TestPagesByOffset_GetCurrent(tt *testing.T) {
	var zeroValue int
	p := &PagesByOffset{Current: &zeroValue}
	p.GetCurrent()
	p = &PagesByOffset{}
	p.GetCurrent()
	p = nil
	p.GetCurrent()
}

func TestPagesByOffset_GetItems(tt *testing.T) {
	var zeroValue int
	p := &PagesByOffset{Items: &zeroValue}
	p.GetItems()
	p = &PagesByOffset{}
	p.GetItems()
	p = nil
	p.GetItems()
}

func TestPagesByOffset_GetMaxSize(tt *testing.T) {
	var zeroValue int
	p := &PagesByOffset{MaxSize: &zeroValue}
	p.GetMaxSize()
	p = &PagesByOffset{}
	p.GetMaxSize()
	p = nil
	p.GetMaxSize()
}

func TestPagesByOffset_GetSize(tt *testing.T) {
	var zeroValue int
	p := &PagesByOffset{Size: &zeroValue}
	p.GetSize()
	p = &PagesByOffset{}
	p.GetSize()
	p = nil
	p.GetSize()
}

func TestPagesByOffset_GetTotal(tt *testing.T) {
	var zeroValue int
	p := &PagesByOffset{Total: &zeroValue}
	p.GetTotal()
	p = &PagesByOffset{}
	p.GetTotal()
	p = nil
	p.GetTotal()
}

func TestRateLimits_GetCore(tt *testing.T) {
	r := &RateLimits{}
	r.GetCore()
	r = nil
	r.GetCore()
}

func TestThreats_GetStatus(tt *testing.T) {
	var zeroValue string
	t := &Threats{Status: &zeroValue}
	t.GetStatus()
	t = &Threats{}
	t.GetStatus()
	t = nil
	t.GetStatus()
}
