name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        goVer: [ 1.15, 1.16 ]
    steps:
#      - uses: actions/checkout@v2

      - name: Cache Go modules
        uses: actions/cache@preview
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Set up Go ${{ matrix.goVer }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.goVer }}


      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Integration Test
        run: go test ./... -tags=integration
