name: Go

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29
  
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.15', '1.16' ]
    name: Go ${{ matrix.go }} Build
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go build --race ./...

      - name: Test
        run: go test --race -v ./...

      - name: Integration Test
        run: go test --race ./... -tags=integration
